### ISSUE TITLE
Prevent saving cache when PR build

### ISSUE THREAD

**Issue by onovotny** [Microsoft/azure-pipelines-artifact-caching-tasks#14]
PR builds often should not be cached as they contain intermediate state and/or are a security risk (in the case of PR builds from public forks).

It would be nice if this task could automatically handle these so people don't accidently cache risky artifacts.

**Comment by jessehouwing** [comment]
Forks are automatically excluded

**Comment by onovotny** [comment]
Perfect, would be great to have that documented as I didn’t see anything about that.

**Comment by jessehouwing** [comment]
https://github.com/Microsoft/azure-pipelines-artifact-caching-tasks/blob/ea4766905de3a42baa1e8fae5a15c90942387d07/Tasks/Common/packaging-common/cache/cacheUtilities.ts#L178-L186

**Comment by jessehouwing** [comment]
https://github.com/Microsoft/azure-pipelines-artifact-caching-tasks/blob/ea4766905de3a42baa1e8fae5a15c90942387d07/Tasks/Common/packaging-common/cache/cacheUtilities.ts#L237-L245

**Comment by jessehouwing** [comment]
Agreed that restore for forks may be useful.

**Comment by erdennis13** [comment]
I updated the Readme with information about why forks are excluded - it's both a design decision and a technical limitation.
