### ISSUE TITLE
Requires tar on the build 

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azure-pipelines-artifact-caching-tasks#18]
The task should really bring its own tools IMHO, or the documentation should include a task to have that tool included in the build pipeline. Having to have all tools installed on the agent is a pointless dead exercise.

Further more the task shouldn't succeed if the tar fails. That's really bad, we had a dev thought everything was great because everything ran fine, only to find it didn't.

Given universal files does dedupe and compression, is there a need for tar?

**Comment by erdennis13** [comment]
We performance tested both using tar to create archives and uploading file sets and using tarballs was faster. 

Also, we built this task to be resilient across failures (network, tar, auth etc.). We'd happily take contributions to display warnings on these failures instead.

**Comment by simonsabin** [comment]
Surprised you've closed this when the task succeeds even though its failed. Plus the docs could do with a mention

**Comment by erdennis13** [comment]
> Also, we built this task to be resilient across failures (network, tar, auth etc.). We'd happily take contributions to display warnings on these failures instead.

I'd be happy to help your team onboard to using this task - if you have any more details or a question to ask. However, we're not going to change the behavior of the task from preventing build failures whenever possible.
