### ISSUE TITLE
Azure Dev Ops Server 2019 Support

### ISSUE THREAD

**Issue by chapterjason** [microsoft/azure-pipelines-artifact-caching-tasks#30]
On the marketplace it says that it also supports Azure Dev Ops Server 2019 but it does not work, cause the server version does not have the universal artifact packages.

![image](https://user-images.githubusercontent.com/1337562/71265334-488b6800-2346-11ea-866c-b45d341d7d58.png)

I'm a bit confused about that, cause in the services version there is the `Cache@v2` usable which does not exist on server. I thought that this would be the alternative but it does not work. 😕

**Comment by erdennis13** [comment]
Sorry for the confusion, @chapterjason! Unfortunately, these tasks will only work with Azure DevOps Services, due to Universal Packages not being available on Server. I'll update the documentation with a note about this limitation.
