### ISSUE TITLE
Add support to project-scoped feeds

### ISSUE THREAD

**Issue by daliran** [Microsoft/azure-pipelines-artifact-caching-tasks#39]
The current implementation only supports organization-scoped feeds but Azure DevOps recommends and allows to create only project-scoped feeds.

https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops#project-scoped-feeds-vs-organization-scoped-feeds

https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops

The workaround is to use the REST API to manually create a organization-scoped feed but since by default only project-scoped feeds are created, it would be nice to add the support for both types.

https://developercommunity.visualstudio.com/content/problem/859583/can-no-longer-create-organization-scoped-feeds.html

**Comment by ethanis** [comment]
Thanks for the feedback, @daliran!

If possible, I suggest that you try out the official [pipeline caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks (they were heavily influenced by these). If the official tasks don't work, I'd love to know what features of this repo's tasks you depend on!

**Comment by daliran** [comment]
Thank you @ethanis , I was not aware about an official pipeline caching task, I will definitely look into that! If that is the case, is this repo still a valid option or is going to be deprecated?

About the features, I only need to cache npm packages between builds.

**Comment by ethanis** [comment]
No problem! The official pipeline caching tasks should give you everything you need out of the box.

There are no current plans to deprecate this repo's tasks, but the official tasks get a lot more maintenance and attention. Plus, in the near-future, the official tasks will have feature-parity with this repo's tasks.
