### ISSUE TITLE
Azure DevOps Server 2020 Support

### ISSUE THREAD

**Issue by yang-xiaodong** [Microsoft/azure-pipelines-artifact-caching-tasks#41]
Hello there, 

Azure DevOps Server 2020 seems to have supported Universal Packages. Is there any plans to support it?

Thanks

**Comment by hmrc87** [comment]
We also updated to DevOps Server 2020 recently.. getting errors with this task:

`2020-10-12T10:48:10.2472377Z ##[section]Starting: Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json
2020-10-12T10:48:10.2679595Z ==============================================================================
2020-10-12T10:48:10.2680380Z Task         : Restore and save cache
2020-10-12T10:48:10.2680985Z Description  : Restores and saves a folder given a specified key.
2020-10-12T10:48:10.2681491Z Version      : 1.0.18
2020-10-12T10:48:10.2681922Z Author       : Microsoft Corp
2020-10-12T10:48:10.2682382Z Help         : 
2020-10-12T10:48:10.2682896Z ==============================================================================
2020-10-12T10:48:13.0594153Z SYSTEMVSSCONNECTION exists true
2020-10-12T10:48:13.0656869Z https://tfs.XXXX.de/tfs/cp01/
2020-10-12T10:48:13.1600316Z ##[warning]Error: Failed to find api location for area: clienttools id: 187ec90d-dd1e-4ec6-8c57-937d979261e5
2020-10-12T10:48:13.1617633Z Error initializing artifact tool utility
2020-10-12T10:48:13.1685016Z ##[warning]Issue running universal packages tools
2020-10-12T10:48:13.1800691Z ##[section]Finishing: Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json`

**Comment by chelito103** [comment]
I have the same error with azure devops 2019

**Comment by michaelfaith** [comment]
We're also experiencing this issue.

**Comment by manuelkroiss** [comment]
Any updates on this issue?

**Comment by ethanis** [comment]
At this time we have no plans to update this task. Please use Azure DevOp's built in [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks which are the successor to these tasks. The tasks in this repo inspired the official tasks but the tasks in this repo are not actively maintained.

**Comment by manuelkroiss** [comment]
Hm...ok..
Sadly, the Azure DevOps built in task does not work on an onPremise Azure Devops 2020 Server (only in DevOps Services in the cloud)

Any suggestions how to implement caching on an onPremise Azure Devops 2020 instance?

**Comment by michaelfaith** [comment]
> At this time we have no plans to update this task. Please use Azure DevOp's built in [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks which are the successor to these tasks. The tasks in this repo inspired the official tasks but the tasks in this repo are not actively maintained.

@ethanis  If that's the case, then the documentation on the marketplace page needs to be updated, because it currently says that it supports Azure DevOps Server 2020.  And like @manuelkroiss said, the built-in task isn't supported for OnPrem.  It's why we're here, because this task documentation says it is.

**Comment by yang-xiaodong** [comment]
Unfortunately, this repository is not maintained. I think this is very helpful for people who use Azure Devops server to build front-end projects. It is difficult for the community to contribute due to lack of understanding of Devops internals

**Comment by chelito103** [comment]
If you go to the documentation, you'll see the version dropdown is set to Azure DevOps Services (i.e. Cloud), if you update the version dropdown to 2020, you'll get a redirect and indicator at the top saying that the feature is not supported on 2020

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops&viewFallbackFrom=azure-devops-2020

I was able to get cache functionality on 2019 by adding script tasks to replicate save/restore functionality.  The below is a hack but it works for an angular 9 project.  Note he tasks were created to work on a windows build agent and cache location is hardcoded in the tasks.  

Update your build pipeline:
Prior to build task:
1.  Add Task: Use Powershell Task (2.7.x) 
2.  Add "Restore from Cache" Task: Powershell Task (inline), working directory = $(Build.SourcesDirectory)
$key_file file is hashed to produce an identifier.  The $cacheRoot is searched for a directory under that identifier, if found then it is restored to $target_folder.

```
 $key_file="package-lock.json"
 $target_folder="node_modules"

 $cacheRoot = (Get-Volume -filepath $pwd).DriveLetter + ":\azCache"
 $keyFilePath= "$pwd\$key_file"
 $targetPath = "$pwd\$target_folder"
 $keyHash = (Get-FileHash $keyFilePath -Algorithm SHA1).Hash

 #Cache does not exist for this key
 if (!(Test-Path "$cacheRoot\$keyHash" -PathType Container)) {
     Write-Output("Cache Miss")
 
     #Set Pipeline Varaible
     Write-Host "##vso[task.setvariable variable=cacheRestored;]false"
 }else{
    Write-Output("Cache Hit")
 
    If(!(test-path $targetPath)){
        #Create Symbolic link to cache
        New-Item -ItemType SymbolicLink -Path "$targetPath" -Target "$cacheRoot\$keyHash\$target_folder"
    }

     #Set Pipeline Varaible
     Write-Host "##vso[task.setvariable variable=cacheRestored;]true"
 }

```

3. Update npm install task Control options (Custom Condition = and(succeeded(), ne(variables['cacheRestored'], 'true')))
    This will ensure that npm install will only execute when cacheRestored is false, if it has been restored then this step will be skipped.
    
4. Updated npm build task to preserve symlinks this will allow angular cli to preserve symlinks in optimization stages like minification etc...
i.e. args: run build -- --configuration prod  --preserve-symlinks true

5. Create post build task (Save To Cache): Powershell Task (inline) working directory = $(Build.SourcesDirectory), control options (Custom Condition = and(succeeded(), ne(variables['cacheRestored'], 'true')))
 
```
 $cacheRoot = (Get-Volume -filepath $pwd).DriveLetter + ":\azCache"
 $keyFilePath= "$pwd\$key_file"
 $targetPath = "$pwd\$target_folder"
 $keyHash = (Get-FileHash $keyFilePath -Algorithm SHA1).Hash
  
 
 Write-Output "Move-Item $targetPath -Destination "$cacheRoot\$keyHash""
 
 New-Item -ItemType Directory -Force -Path $cacheRoot\$keyHash
 Move-Item $targetPath -Destination "$cacheRoot\$keyHash" -Force 

```

**Comment by michaelfaith** [comment]
> If you go to the documentation, you'll see the version dropdown is set to Azure DevOps Services (i.e. Cloud), if you update the version dropdown to 2020, you'll get a redirect and indicator at the top saying that the feature is not supported on 2020
> 

Talking about this: 
![image](https://user-images.githubusercontent.com/8071845/122453321-d8c46080-cf6f-11eb-8a1a-dc083fe0f852.png)
