### ISSUE TITLE
[Question] Is this still maintained?

### ISSUE THREAD

**Issue by hmrc87** [Microsoft/azure-pipelines-artifact-caching-tasks#43]
Hi, is this project still supported/maintained by Microsoft?

**Comment by ethanis** [comment]
@hmrc87 this project was an experimental project which inspired the office [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks for Azure Pipelines. If possible, you should use the official tasks as they are officially maintained by Azure DevOps.

**Comment by hmrc87** [comment]
Thanks, however unfortunately not available for Azure DevOps Server :(
