### ISSUE TITLE
using caching tasks on private build server without tar

### ISSUE THREAD

**Issue by hansterwal** [Microsoft/azure-pipelines-artifact-caching-tasks#5]
Hi,

When creating the archive for the cache, a tar command is executed.

[cshell.exec(`tar -xzf ${tarballPath} -C "${destinationFolder}"`);](https://github.com/Microsoft/azure-pipelines-artifact-caching-tasks/blob/master/Tasks/Common/packaging-common/cache/cacheUtilities.ts)

This works fine on hosted 2017 agents but not on our private win2016 core agents.

Looking over the list of tools installed on a hosted vs2017 image I cannot find tar among them. 

Can you point me in the right direction of which set of tools should be installed on our build servers
to get the task to work?

Kind regards,

Hans ter Wal

**Comment by erdennis13** [comment]
`bsdtar` is what gets installed onto Windows by default now. You can get releases of this [here](http://libarchive.org/).

If this unblocks you, I'd love to see this added this to the documentation!

**Comment by hansterwal** [comment]
Hi Ethan,

I downloaded, compiled and added the bsdtar as tar.exe to the path of the server and restarted the vsts agent. Unfortunately i'm still getting an "
'tar' is not recognized as an internal or external command".

Is there a special setup required to use it with cshell.exe?

**Comment by erdennis13** [comment]
There isn't a cshell.exe. The typescript is referencing `shell` from `shelljs`. Can you verify that `where tar` from a command prompt returns the path to the tar.exe you compiled?

**Comment by erdennis13** [comment]
That looks like a permissions error to me. Can you share the folder permissions for `c:\vsts-agent`?

**Comment by hansterwal** [comment]
CREATOR OWNER
SYSTEM
Administrators
Users

No agent service to the root c:\vsts-agent.

Now I changed two things 
1-  added VSTS_AgentService_XXXXX to have full control on the c:\VSTS-agent folder
2- I changed our win2016 server to win2019  (to have default tar experience out of the box)

Now I'm getting:

tar -C "/C/VSTS-agent/agent1/_work/1/s" -czfv "/C/VSTS-agent/agent1/_work/1/s/tmp_cache/win32-8a285725f109f9d1d20adc55d799136b707eef062ef5abf7713b031bc53425b8.tar.gz" "Src/Fh.Lhd.Rct/node_modules"
"Src/Fh.Lhd.Rct/node_modules"
/C/VSTS-agent/agent1/_work/1/s/tmp_cache/win32-8a285725f109f9d1d20adc55d799136b707eef062ef5abf7713b031bc53425b8.tar.gz
Issue creating tarball:
    tar: /C/VSTS-agent/agent1/_work/1/s/tmp_cache/win32-8a285725f109f9d1d20adc55d799136b707eef062ef5abf7713b031bc53425b8.tar.gz: Couldn't find file: No such file or directory
tar: could not chdir to '/C/VSTS-agent/agent1/_work/1/s'

**Comment by erdennis13** [comment]
Can you email me the build logs? etdenn at microsoft dot com

Also, just to confirm, the win2019 build agent is your own machine (not hosted)?

**Comment by hansterwal** [comment]
Well I finally got it working using the azure images pipeline scripts.

https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-7zip.ps1

and

https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-Git.ps1

The last one adds the tar.exe to the path using the following line

Add-MachinePathItem "C:\Program Files\Git\usr\bin"
