### ISSUE TITLE
Tar Issues - Error opening archive and cleaning up compressor on Windows Image

### ISSUE THREAD

**Issue by Cdoherty95** [Microsoft/azure-pipelines-artifact-caching-tasks#50]
We are seeing an issue when using the Restore and save cache task on a Microsoft Hosted Agent running a Windows image. The task runs just fine, with the same configuration, when we use a Linux image. We are trying to cache npm packages for our angular application but cannot seem to figure out this tar issue while running on a Windows image. Issue #35 is the same error we are getting but the issue has been closed for a few months now.

The error we get when restoring is: `tar: Error opening archive: Failed to open '/D/a/1/s/tmp_cache/aaa579713b25a5a1b4e37b99c571beadb0b1ec3592e007eb503ac631.tar.gz'`

The error we get when saving is: `Issue creating tarball: tar: Failed to clean up compressor`

Windows Image: windows-2019
Key file: RepositoryRoot\AngularApplication\package-lock.json
Target folder: RepositoryRoot\AngularApplication\node_modules

Running on Image: ubuntu-20.04 with the same Key file and Target folder the Restore and save cache task runs as expected.

I think the error when restoring might be a path issue. On both images, it tries to use a Linux path `/D/`. On the Windows image, I think it needs to be `D:/`.

Please let me know if more details are needed. Any help would be appreciated!

_Originally posted by @temparnak in https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/issues/35#issuecomment-617008337_

**Comment by ethanis** [comment]
@Cdoherty95 sorry to hear that you've been running into this issue. Have you tried to use the Azure DevOp's built in [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks which are the successor to these tasks? The tasks in this repo inspired the official tasks but the tasks in this repo are not actively maintained.

**Comment by Cdoherty95** [comment]
Thanks for the reply. I was really hoping to use this task but I will give the [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) task a shot
