### ISSUE TITLE
restore cache step failed: error initializing artifact tool utility

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azure-pipelines-artifact-caching-tasks#51]
this is the log:

Starting: RestoreCache
==============================================================================
Task         : Restore cache
Description  : Restore a folder from a cache given a specified key.
Version      : 1.0.18
Author       : Microsoft Corp
Help         : 
==============================================================================
SYSTEMVSSCONNECTION exists true
got service url from area
https://mssqltools.vsblob.visualstudio.com/
Downloading: https://004vsblobprodeus2116.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.181.zip?sv=2019-07-07&sr=b&sig=e7oXCKTrMTp2uLwsKJL9In%2F84fmfwNKu9RIm2AN6iTM%3D&spr=https&se=2021-01-26T00%3A02%3A09Z&sp=r&P1=1611619029&P2=11&P3=2&P4=FmRDql35kTtX0YYO6P3yqFewc9Ttt7suhcmJj7mPR8Q%3d
##[warning]Invalid or unsupported zip format. No END header found
Error initializing artifact tool utility
##[warning]Issue running universal packages tools
Finishing: RestoreCache

**Comment by alanrenmsft** [comment]
this happened again today, we enabled debugging flag.

##[debug]applying include pattern
##[debug]adjustedPattern: '/__w/1/s/.build/quality'
##[debug]1 matches
##[debug]3 final results
##[debug]Found key file: /__w/1/s/.build/commit
##[debug]Found key file: /__w/1/s/.build/quality
##[debug]Found key file: /__w/1/s/build/.cachesalt
##[debug]System.DefaultWorkingDirectory=/__w/1/s
##[debug]Absolute path for pathSegments: /__w/1/s/.build/commit = /__w/1/s/.build/commit
##[debug]Absolute path for pathSegments: /__w/1/s/.build/quality = /__w/1/s/.build/quality
##[debug]Absolute path for pathSegments: /__w/1/s/build/.cachesalt = /__w/1/s/build/.cachesalt
##[debug]platformIndependent=true
##[debug]System.DefaultWorkingDirectory=/__w/1/s
##[debug]testing directory '/__w/1/s/tmp_cache'
##[debug]testing directory '/__w/1/s'
##[debug]mkdir '/__w/1/s/tmp_cache'
##[debug]dryRun=false
##[debug]alias=Compilation
##[debug]Getting artifact tool
##[debug]Getting credentials for local feeds
SYSTEMVSSCONNECTION exists true
##[debug]SYSTEMVSSCONNECTION exists true
##[debug]Got auth token
##[debug]SYSTEMVSSCONNECTION=https://mssqltools.visualstudio.com/
##[debug]System.ServerType=Hosted
##[debug]Agent.ProxyUrl=undefined
##[debug]Getting URI for area ID 5294ef93-12a1-4d13-8671-9d9d014072c8 from https://mssqltools.visualstudio.com/
got service url from area
https://mssqltools.vsblob.visualstudio.com/
##[debug]UPack.OverrideArtifactToolPath=undefined
##[debug]Agent.ProxyUrl=undefined
##[warning]Error: Failed request: (503)
##[debug]Processed: ##vso[task.issue type=warning;]Error: Failed request: (503)
Error initializing artifact tool utility
##[warning]Issue running universal packages tools
##[debug]Processed: ##vso[task.issue type=warning;]Issue running universal packages tools
##[debug]rm -rf /__w/1/s/tmp_cache
##[debug]removing directory
##[debug]Handler exit code: 0
Finishing: RestoreCache

**Comment by ethanis** [comment]
@alanrenmsft  sorry to hear that you've been running into this issue. Have you tried to use the Azure DevOp's built in [Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops) tasks which are the successor to these tasks? The tasks in this repo inspired the official tasks but the tasks in this repo are not actively maintained.

**Comment by alanrenmsft** [comment]
I'll definitely try it out. Thanks!
