### ISSUE TITLE
"Step references task '1ESLighthouseEng....' which does not exist." Error

### ISSUE THREAD

**Issue by wmhilton** [Microsoft/azure-pipelines-artifact-caching-tasks#6]
Hi! I read your [blog post](https://medium.com/microsoft-1es/reducing-vs-code-ci-build-times-e0c5872bfdde) (linked in the VS Code [release notes](https://code.visualstudio.com/updates/v1_33#_caching-npm-packages)) and thought it sounded like a thing I should try! 

But I get this error:
```
Job Linux: Step references task '1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache' at version '1' which does not exist.
```
![image](https://user-images.githubusercontent.com/587740/55594513-e504d000-570d-11e9-9c72-5aa408296d14.png)

which makes me think I'm missing some basic beginner step like "installing" the task or something.

Azure build page: https://dev.azure.com/isomorphic-git/isomorphic-git/_build/results?buildId=847&view=results

Got any suggestions?

**Comment by erdennis13** [comment]
I'm happy to hear you're trying out the build task (although sorry to hear the onboarding hasn't been a breeze). Have you installed tasks through the [marketplace](https://marketplace.visualstudio.com/items?itemName=1ESLighthouseEng.PipelineArtifactCaching)?

**Comment by erdennis13** [comment]
Another step you'll need to take is to have a build variable (`ArtifactFeed`) that points to the guid of an [Azure Artifacts](https://azure.microsoft.com/en-us/services/devops/artifacts/) feed in your Azure DevOps instance.

**Comment by denu5** [comment]
It would be really helpful to point out in the docs that **azure artifacts** needs to be enabled - not knowing about it made it quite hard to find out how it works

**Comment by wmhilton** [comment]
> Have you installed tasks through the marketplace?

Aha! That's exactly the kind of step I thought I might be missing. Awesome 😊

**Comment by wmhilton** [comment]
> Another step you'll need to take is to have a build variable (ArtifactFeed) that points to the guid of an Azure Artifacts feed in your Azure DevOps instance.

OK, so I've created an Artifact Feed but now I'm at a loss how to find it's GUID.

**Comment by erdennis13** [comment]
You are all absolutely correct that we can provide better info for onboarding. I've updated the readme to include some more information for onboarding. Let me know if this helps clear things up..

 > _Note:_ The GUID for your Azure Artifact feed can be found either by using the Azure DevOps [rest apis](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/get%20feeds?view=azure-devops-rest-5.0#response) or by creating a build task in the traditional visual designer that references the feed and then selecting "View YAML".

**Comment by wmhilton** [comment]
Awesome! Yeah, the onboarding could be polished. I'd love it to simply be baked into the regular ["get started with Node" tutorials](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops)

Happy to say it was a big win! Cut my `npm ci` time in half from over a minute to 34s!
https://github.com/isomorphic-git/isomorphic-git/pull/723
